---
title: "20191029_in_class_17"
author: "Gaotong LIU"
date: "10/29/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
set.seed(1)
```

# List
```{r}
vec_numeric = 5:8
vec_char = c("My", "name", "is", "Jeff")
vec_logical = c(TRUE, TRUE, TRUE, FALSE)
```

```{r}
l = list(vec_numeric = 5:8,
         mat         = matrix(1:8, 2, 4),
         vec_logical = c(TRUE, FALSE),
         summary = summary(rnorm(1000)))
l
l$vec_numeric
l[[1]]
l[[1]][1:3]
```

```{r}
df = tibble(
  a = rnorm(20, 3, 1),
  b = rnorm(20, 0, 5),
  c = rnorm(20, 10, .2),
  d = rnorm(20, -3, 1)
)

df$a
df[[2]]
```

```{r}
mean_and_sd = function(x) {
if (!is.numeric(x)) {
stop("Argument x should be numeric")
} else if (length(x) == 1) {
stop("Cannot be computed for length 1 vectors")
}
  mean_x = mean(x)
  sd_x = sd(x)
  tibble(
    mean = mean_x,
    sd = sd_x
  ) }

mean_and_sd(df[[1]])
mean_and_sd(df[[2]])
mean_and_sd(df[[3]])
mean_and_sd(df[[4]])
```

# For loop
```{r}
output = vector("list", length = 4)

for (i in 1:4){
  output[[i]] = mean_and_sd(df[[i]])
}

output = map(df, mean_and_sd)
output_summary = map(df, summary)

output = map(df, mean_and_sd)
output = map(.x = df, ~ median(.x))
```

## Examples
```{r}
read_page_reviews = function(url) {
  h = read_html(url)
  title = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  text = h %>%
    html_nodes(".review-data:nth-child(5)") %>%
    html_text()
  data_frame(title, stars, text)
}

url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url_base, 1:5)

output = vector("list", length = 5)
for (i in 1:5){
  output[[i]] = read_page_reviews(vec_urls[[i]])
}

output = map(vec_urls, read_page_reviews)
```

##List columns
```{r}
weather =
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"),
    date_min = "2016-01-01",
    date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY",
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

```

# Nest within station
```{r}
weather_nest =
  nest(weather, data = date:tmin) 
```

## Is a list column  a list?
```{r}
weather_nest %>% pull(name)
weather_nest %>% pull(data)
```

## Usefull things
```{r}
central_park_df = weather_nest$data[[1]]
lm(tmax ~ tmin, data = central_park_df)

lm(tmax ~ tmin, data = weather_nest$data[[1]])
lm(tmax ~ tmin, data = weather_nest$data[[2]])
lm(tmax ~ tmin, data = weather_nest$data[[3]])

# FOR LOOP
output = vector("list", length = 3)

for (i in 1:3) {
  output[[i]] = lm(tmax ~ tmin, data = weather_nest$data[[i]])
}

# Function
weather_lm = function(df){
  lm(tmax ~ tmin, data = df)
}

for (i in 1:3) {
  output[[i]] = weather_lm(weather_nest$data[[i]])
}

# Map
output = map(weather_nest$data, weather_lm)
```

# Add list column in  original df
```{r}
weather_nest %>% 
  mutate(lin_models = map(data, weather_lm))
```

```{r}
tibble(
  page = 1:5,
  urls = str_c(url_base, page)
) %>% 
  mutate(
    reviews = map(urls, read_page_reviews)
  ) %>% 
  unnest() %>% 
  select(-urls)
```


```{r}
split = 
  cancer %>% 
  nest(data = survival) %>% 
  mutate(mean = map(data, ~mean(.x$survival))) %>% 
  select(-data) %>% 
  unnest(mean)
  
  pivot_wider(values_from = survival,
                       names_from = organ)

```




