---
title: "Homicide and simulation"
author: "Gaotong LIU"
date: "10/31/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
set.seed(1)
```

# Extra example
## Read in the data

The data come from [here](https://github.com/washingtonpost/data-homicides).

```{r}
homicide_df = 
  read_csv("data/homicide-data.csv", na = c("", "NA", "Unknown")) %>%
  mutate(
    city_state = str_c(city, state, sep = ", "),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved"
    )
  ) %>% 
  filter(city_state != "Tulsa, AL") 
```

## Aggregate at the city level

```{r}
city_homicide_df =
  homicide_df %>% 
  select(city_state, resolution, disposition) %>% 
  group_by(city_state) %>% 
  summarize(
    hom_unsolved = sum(resolution == "unsolved"),
    hom_total = n()
  )
```

## For one city ...
... get the estimated rate of unsolved homicides and CI using `prop.test()` and `broom::tidy()`

```{r}
prop.test(
  x = city_homicide_df %>% filter(city_state == "Tulsa, OK") %>% pull(hom_unsolved), 
  n = city_homicide_df %>% filter(city_state == "Tulsa, OK") %>% pull(hom_total)) %>% 
  broom::tidy()
```

## Repeat for all cities

```{r}
homicide_results = 
  city_homicide_df %>% 
  mutate(
    prop_test = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)),
    estimate_df = map(prop_test, broom::tidy)) %>% 
  select(city_state, estimate_df) %>% 
  unnest(estimate_df) %>% 
  select(city_state, estimate, conf.low, conf.high) %>% 
  mutate(city_state = fct_reorder(city_state, estimate))
```

## Visualize results

```{r}
homicide_results %>% 
  ggplot(aes(x = city_state, y = estimate)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +  
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

# simulation

```{r}
set.seed(1)
```

## simple regression function

```{r}
sim_regression = function(n, beta0 = 2, beta1 = 3) {
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 1)
)
  ls_fit = lm(y ~ x, data = sim_data)
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
) }
```

```{r}
sim_regression(n = 30)
```

## rerun simulation using For loop

```{r}
output  = vector("list", length = 500)

for (i in 1:500) {
  output[[i]] = sim_regression(n = 30)
}

bind_rows(output) %>% 
  ggplot(aes(x = beta0_hat)) + geom_density()
```

## rerun simulation using `purrr`

```{r}
output = 
  rerun(500, sim_regression(n = 30)) %>% 
  bind_rows() 

output %>% 
  ggplot(aes(x = beta0_hat)) + geom_density()

output %>% 
  ggplot(aes(x = beta0_hat, y = beta1_hat)) + geom_point()

```

```{r}
sim_data = tibble(
    x = rnorm(30, mean = 1, sd = 1),
    y = 2 + 3 * x + rnorm(30, 0, 1)
)

sim_data %>% 
  ggplot(aes(x = x, y = y)) + geom_point() +
  stat_smooth(method = "lm", se = FALSE)

```


```{r}
output %>%
  pivot_longer(beta0_hat:beta1_hat,
    names_to =  "parameter", 
    values_to  = "estimate") %>%
  group_by(parameter) %>%
  summarize(emp_mean = mean(estimate),
            emp_var = var(estimate)) %>%
  knitr::kable(digits = 3)
```

## try other sample size
```{r}
n_list = list("n_30"  = 30,
              "n_60"  = 60,
              "n_120" = 120,
              "n_240" = 240)

output = vector("list", length = 4)

for (i in 1:4) {
output[[i]] = rerun(1000, sim_regression(n_list[[i]])) %>%
bind_rows }

output[[4]] %>% 
  ggplot(aes(x = beta0_hat)) + geom_density()
```

```{r}
sim_results = tibble(
  sample_size = c(30, 60, 120,  240)
) %>% 
  mutate(output_list = map(.x = sample_size, ~rerun(1000, sim_regression(n = .x))),
         output_df = map(output_list, bind_rows)) %>% 
  select(-output_list) %>% 
  unnest(output_df)
  
```

```{r}
sim_results %>% 
  group_by(sample_size) %>% 
  summarise(var_b1 = var(beta1_hat))
```

```{r}
sim_results %>%
  mutate(
    sample_size = str_c("n = ", sample_size),
    sample_size = fct_inorder(sample_size)) %>%
  ggplot(aes(x = beta0_hat, y = beta1_hat)) +
  geom_point(alpha = .2) +
  facet_grid(sample_size~.)

sim_results %>%
  mutate(
    sample_size = str_c("n = ", sample_size),
    sample_size = fct_inorder(sample_size)) %>%
  ggplot(aes(x = sample_size, y = beta1_hat, fill = sample_size)) +
  geom_violin()
```







