---
title: "20191001_in_class_9"
author: "Gaotong LIU"
date: "10/1/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
library(patchwork)
```

## reate the weather data

```{r load  data, message=FALSE, cache=TRUE}
# save data cache
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```
## making new plots
### add labels
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    caption = "Data from NOAA via rnaa package"
    ) +
  scale_x_continuous(
    breaks = c(-15, -5, 20),
    labels = c("-15C", "-5(still too cold)", "20")
  ) +
   scale_y_continuous(
    trans = "sqrt",
    position = "right") +
  scale_y_sqrt()
```
### add colors
```{r}
# hue: h not suggest
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    caption = "Data from NOAA via rnaa package"
    ) +
  scale_color_hue(
    name = "Location",
    h = c(50, 300)
  )
```

```{r}
ggp_base = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    caption = "Data from NOAA via rnaa package"
    ) +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  )
```

## themes
```{r}
ggp_base +
  theme_bwl() +
  theme(legend.position = "bottom")

ggp_base +
  theme_minimal() +
  theme(legend.position = "bottom")

# order: overall first, them details
ggp_base +
  theme(legend.position = "bottom") +
  theme_minimal() 
```

## more than one dataset

```{r}
central_park =
  weather_df %>%
  filter(name == "CentralPark_NY")
waikiki =
  weather_df %>%
  filter(name == "Waikiki_HA")

ggplot(data = waikiki, aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp)) +
  geom_line(data = central_park)

ggplot(data = waikiki, aes(x = date, y = tmax, color = "blue")) +
  geom_point()

ggplot(data = waikiki, aes(x = date, y = tmax)) +
  geom_point(color = "blue", alpha = .5)
```

## Multi-panel plots: patchwork
```{r}
tmax_tmin_p =
  weather_df %>%
  ggplot(aes(x = tmax, y = tmin, color = name)) +
  geom_point(alpha = .5) +
  theme(legend.position = "none")
prcp_dens_p =
  weather_df %>%
  filter(prcp > 0) %>%
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = .5) +
  theme(legend.position = "none")
tmax_date_p =
  weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) +
  theme(legend.position = "bottom")

(tmax_tmin_p + prcp_dens_p) / tmax_date_p
tmax_tmin_p + (prcp_dens_p / tmax_date_p)
```

## data manipultation: factor
```{r}
# ggplot order == factor
weather_df %>% 
  ggplot(aes(x =  name, y = tmax, color = name)) +
  geom_boxplot()

weather_df %>%
  mutate(name = forcats::fct_relevel(name, c("Waikiki_HA", "CentralPark_NY", "Waterhole
_WA"))) %>%
  ggplot(aes(x = name, y = tmax, color = name)) +
  geom_boxplot()
```

## restructure the plot
```{r}
weather_df %>%
  select(name, tmax, tmin) %>%
  pivot_longer(
    tmax:tmin,
    names_to = "observation",
    values_to = "temp") %>%
  ggplot(aes(x = temp, fill = observation)) +
  geom_density(alpha = .5) +
  facet_grid(~name) +
  viridis::scale_fill_viridis(discrete = TRUE)
```

```{r}
pulse_data =
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi") %>%
  select(id, visit, everything()) %>%
  mutate(visit = recode(visit, "bl" = "00m"),
         visit = factor(visit, levels = str_c(c("00", "01", "06", "12"), "m"))) %>%
  arrange(id, visit)
ggplot(pulse_data, aes(x = visit, y = bdi)) +
  geom_boxplot()
```

```{r}
pup_data =
  read_csv("./data/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female"))
litter_data =
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  separate(group, into = c("dose", "day_of_tx"), sep = 3) %>%
  mutate(wt_gain = gd18_weight - gd0_weight,
         day_of_tx = as.numeric(day_of_tx))
fas_data = left_join(pup_data, litter_data, by = "litter_number")
fas_data %>%
  select(sex, dose, day_of_tx, pd_ears:pd_walk) %>%
  pivot_longer(
    pd_ears:pd_walk,
    names_to = "outcome",
    values_to = "pn_day") %>%
  drop_na() %>%
  mutate(outcome = forcats::fct_reorder(outcome, day_of_tx, median)) %>%
  ggplot(aes(x = dose, y = pn_day)) +
  geom_violin() +
  facet_grid(day_of_tx ~ outcome)
```

```{r}
fas_data %>% 
  ggplot(aes(x = dose, y = pd_ears)) +
  geom_violin() +
  facet_grid(~day_of_tx)
```


```{r}
fas_data %>%
  select(sex, dose, day_of_tx, pd_ears:pd_walk) %>%
  pivot_longer(
    pd_ears:pd_walk,
    names_to = "outcome",
    values_to = "pn_day") %>%
  drop_na() %>%
  mutate(outcome = forcats::fct_reorder(outcome, day_of_tx, median)) %>%
  ggplot(aes(x = dose, y = pn_day)) +
  geom_violin() +
  facet_grid(day_of_tx ~ outcome)
```












