---
title: "20191003in_class_10"
author: "Gaotong LIU"
date: "10/3/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## create the weather data

```{r load_data, cache = TRUE}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, date, month, everything())
```

## group _by and counting
```{r}
weather_df %>% 
  group_by(name, month)
```

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    n_obs = n(),
    n_unique = n_distinct((date)))
```

```{r}
weather_df %>% 
  count(month, name = "days")
weather_df %>% 
  count(name)
```

## nice table
```{r}
weather_df %>% 
  count(name) %>% 
  knitr::kable()
```

##(2 x 2 table)
```{r}
weather_df %>% 
  filter(name != "Waikiki_HA") %>% 
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5~ "not cold",
      TRUE  ~ "")
  ) %>% 
  group_by(name, cold) %>% 
  count() %>% 
  pivot_wider(
    names_from = "cold",
    values_from = "n"
  )

weather_df %>% 
  filter(name != "Waikiki_HA") %>% 
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5~ "not cold",
      TRUE  ~ "")
  ) %>% 
  janitor::tabyl(name,cold) %>% 
  knitr::kable()
```

## general summaries
```{r}
weather_df %>% 
  group_by(name) %>% 
  summarize(
    n = n(),
    mean_tmax = mean(tmax, na.rm = T),
    sd_tmax = sd(tmax,na.rm = T),
    median_prcp = median(prcp,na.rm = T)
  )
weather_df %>% 
  filter(is.na(prcp))
```

```{r, eval=FALSE}
weather_df %>% 
  group_by(month,name) %>% 
  summarize(
    n = n(),
    mean_tmax = mean(tmax, na.rm = T),
    sd_tmax = sd(tmax,na.rm = T),
    median_prcp = median(prcp,na.rm = T)
  ) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
    geom_point() + geom_line() +
    theme(legend.position = "bottom")

```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>%
  pivot_wider(
    names_from = name,
    values_from = mean_tmax) %>%
  knitr::kable(digits = 1)
```

## grouped mutates
```{r}
weather_df %>% 
  group_by(name) %>% 
  ungroup()
```

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    mean_tmax = mean(tmax,na.rm = T),
    centered_tmax = tmax - mean_tmax
  ) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) +
  geom_point()
```

## winder functons in grouped mutate
```{r}
weather_df %>%
  group_by(name, month) %>%
  filter(min_rank(desc(tmax)) < 4)
```
### lags and leads
```{r}
weather_df %>%
  group_by(name) %>%
  mutate(lagged_tmax = lag(tmax),
    temp_change = tmax - lag(tmax)) %>% 
  summarize(sd_temp_change = sd( temp_change, na.rm = T))
```






















































