---
title: "P8105_Plots_in_class_8"
author: "Gaotong LIU"
date: "9/26/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
```

## reate the weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

### create a ggplot
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

### alternate way of making this plot

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

### sacing initiial plots: mostly do not
```{r}
scatterplot = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

```
### adding color
 
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = .3)
```

###why do `aes` positions matter?
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) + 
  geom_smooth(se = FALSE)
```
###facet!!!
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) + 
  geom_smooth(se = FALSE) +
  facet_grid(~name)
```

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .4) +
  geom_smooth(size = 2, se = FALSE)

```

## Some extra stuff
```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_smooth(size = 2, se = FALSE)
```

### 2d density
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()
```

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_bin2d()
```

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_density2d()
```
## More kinds of plots-univariate plots
```{r}
weather_df %>%
  ggplot(aes(x = tmin, color = name)) +
  geom_histogram()

weather_df %>%
  ggplot(aes(x = tmin, fill = name)) +
  geom_histogram()

weather_df %>%
  ggplot(aes(x = tmin, fill = name)) +
  geom_histogram(position = "dodge") +
  facet_grid(~name)
```
### density plots
```{r}
weather_df %>%
  ggplot(aes(x = tmin, fill = name)) +
  geom_density(alpha = .3) +
  geom_rug()
```
###boxplot
```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()
```
###violin plot
```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_violin(aes(fill = name), color = "blue", alpha = .5)
```
###ridge plot and save
```{r}
gg_ridge_temp = 
  weather_df %>% 
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges(scale = .85)

ggsave("ggplot_ridge_temp.pdf", 
       gg_ridge_temp)
```


###embeding plots to Rmd
```{r, fig.width = 12}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) + 
  geom_smooth(se = FALSE) +
  facet_grid(~name)
```

```{r, fig.width = 6}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) + 
  geom_smooth(se = FALSE) +
  facet_grid(~name)
```

```{r, fig.width = 6, fig.asp = .6, out.width = "90%"}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) + 
  geom_smooth(se = FALSE) +
  facet_grid(~name)
```

```{r, fig.width = 6, out.width = "90%"}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) + 
  geom_smooth(se = FALSE) +
  facet_grid(~name)
```




















