---
title: "20191024_in_class_16"
author: "Gaotong LIU"
date: "10/24/2019"
output: 
  github_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
set.seed(1)
```

## Get started 
### Write some functions.
```{r}
x = rnorm(n = 30, mean = 4, sd = 2.3)
y = rnorm(n = 30, mean = 24, sd = 2.3)
(x - mean(x))/sd(x)
```

```{r}
z_score = function(x){
  (x - mean(x))/sd(x)
  
}

z_score = function(x){
  if(!is.numeric(x)){
    stop("x shoulb be numeric")}
  else if(length(x) == 1){
    stop("Z scores cannot be computed for length 1 vectors")}
  (x - mean(x))/sd(x)
  
}
```

### Try out the funtion

```{r}
z_score(x = c(1:10))
z_score(y)


```

## Multiple outputs
```{r}
mean_and_sd = function(x){
  if(!is.numeric(x)){
    stop("x shoulb be numeric")
    }
  else if(length(x) == 1){
    stop("Z scores cannot be computed for length 1 vectors")
    }
  tibble(
   mean_input = mean(x),
   sd_input = sd(x)
   )
}

mean_and_sd = function(x){
  if(!is.numeric(x)){
    stop("x shoulb be numeric")
    }
  else if(length(x) == 1){
    stop("Z scores cannot be computed for length 1 vectors")
    }
  list(
   mean_input = mean(x),
   sd_input = sd(x),
   z_score = (x - mean(x))/sd(x)
   )
}

mean_and_sd(y)
```

## Multiple inputs
```{r}
sim_data = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

ls_fit = lm(y ~ x, data = sim_data)

beta0_hat = coef(ls_fit)[1]
beta1_hat = coef(ls_fit)[2]
```

```{r}
sim_regression = function(n, beta0 = 2, beta1) {
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 1)
)
  ls_fit = lm(y ~ x, data = sim_data)
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
) }
```

```{r}
sim_regression(3000, 2, 3)
sim_regression(n = 3000, beta0 = 17, beta1 = -3)
```

## Examples
```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)
review_titles = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-title") %>%
  html_text()
review_stars = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()
review_text = dynamite_html %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()
reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

```{r}
read_page_reviews <- function(url) {
 h = read_html(url)
  review_titles = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  review_stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  review_text = h %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()
  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
) }
```

```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url_base, 1:5)
dynamite_reviews = bind_rows(
  read_page_reviews(vec_urls[1]),
  read_page_reviews(vec_urls[2]),
  read_page_reviews(vec_urls[3]),
  read_page_reviews(vec_urls[4]),
  read_page_reviews(vec_urls[5])
)

```

