---
title: "20191008_in_class_11"
author: "Gaotong LIU"
date: "10/8/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(viridis)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
library(p8105.datasets)
data("nyc_airbnb")
``` 

* how are airbnb prices related to rent in the neighbourhood?
```{r}
nyc_airbnb %>% 
  group_by(neighbourhood, neighbourhood_group) %>% 
  summarize(mean_price = mean(price)) %>% 
  ggplot(aes(x = neighbourhood_group, y = mean_price, color = neighbourhood)) +
  geom_point() +
  geom_line()

nyc_airbnb = nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2,
         borough = neighbourhood_group)

nyc_airbnb %>% 
  mutate(neighbourhood = as.factor(neighbourhood)) %>% 
  filter(borough == "Manhattan") %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, price, 
                                     na.rm = TRUE))%>%  
  ggplot(aes(x = price, y = neighbourhood_group)) +
  geom_violin()
```

* which neighbourhood is most expensive and which is cheapst?
* do hosts with multiply sites have higher prices or ratings?
* does price have any relation to ratings?
* is average length of stay related to neighbourhood? price?etc?

```{r}
nyc_airbnb %>% 
  group_by(borough, room_type) %>% 
  summarize(med_price = median(price, na.rm = T)) %>% 
  pivot_wider(
    names_from = room_type,
    values_from = med_price
  )
```
```{r}
nyc_airbnb %>% 
  filter(borough == "Staten Island",
         room_type == "Shared room")

nyc_airbnb %>% 
  count(borough, room_type) %>% 
  pivot_wider(
    names_from = room_type,
    values_from = n
  )
```
 
```{r}
nyc_airbnb %>% 
  group_by(neighbourhood, borough) %>% 
  summarize(
    mean_price = mean(price, na.rm = T),
    mean_review = mean(review_scores_location)
  ) %>% 
  ggplot(aes(x = mean_review, y = mean_price)) +
  geom_point() +
  facet_grid(~borough)

nyc_airbnb %>% 
  filter()
```

## spatial location
```{r}
nyc_airbnb %>% 
  filter(borough == "Manhattan",
         price < 1000) %>% 
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = .3) +
  facet_grid(~room_type)
```

## leaflet for mapping
```{r}
library(leaflet)
nyc_airbnb %>% 
  filter(borough == "Manhattan",
         price > 2000) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addMarkers(~lat, ~long)



pal = colorNumeric(
  palette = "viridis",
  domain = nyc_airbnb$stars)

nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  sample_n(1000) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(
    ~lat, ~long,
    color = ~pal(stars),
    radius = 1
  )
  


nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  mutate(
    label = str_c("<b>Sytars: ", stars, "</b><br>Price: ", price, sep = "")
  ) %>% 
  sample_n(1000) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(
    ~lat, ~long,
    color = ~pal(viridis)
  )
```










